#!/usr/bin/env python3

import fileinput

def main():
    i = 0
    for line in fileinput.input():
        if i == 0:
            print('---')
            print('autogen:', 'This file was automatically generated by ' +
                    'kernel-doc-text-to-markdown.py')
        elif i == 1:
            print('title:', line[7:-1])
            print('---')
            print()
        elif line.startswith('.'):
            # kerneldoc parsing script joins any line ending with '\' to
            # the next line. So, if we need a line that ends in '\', we
            # "reverse-escape" it with '$', then remove the escape here.
            print(line[1:-1].replace('\\$', '\\'))
        else:
            print(line[:-1].replace('\\$', '\\'))
        i += 1

if __name__ == "__main__":
    main()
