#!/usr/bin/env python3

import fileinput

def main():
    i = 0
    for line in fileinput.input():
        if i == 0:
            print('---')
            print('autogen:', 'This file was automatically generated by ' +
                    'kernel-doc-text-to-markdown.py')
        elif i == 1:
            print('title:', line[7:-1])
            print('---')
            print()
        elif line.startswith('.'):
            print(line[1:-1])
        else:
            print(line[:-1])
        i += 1

if __name__ == "__main__":
    main()
